common_params:
  GeoRegion: &GR
    region: EUR
    agr: EUR
    grg_grid_spacing: 0.25
    land_frac_min: 0.25
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
    min_duration: 7
  time_params: &TIME
    start: 1961
    end: 2024
    period: annual
    ref_period: 1961-1990
    cc_period: 2010-2024
  dataset: &DATA
    dataset: ERA5
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/daily/
    statpath: &statpath /data/arsclisys/normal/clim-hydro/TEA-Indicators/static/
    maskpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ # *statpath
    mask_sub: masks/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/results/
  recalc_threshold: false
  recalc_daily: true
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true

create_region_masks:
  <<: *GR
  <<: *PATHS
  <<: *DATA
  <<: *PARAM
  <<: *TIME
  gr_type: polygon
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/ERA5_orography.nc
  lsmfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/ERA5_LSM.nc
