common_params:
  GeoRegion: &GR
    region: AUT
  parameter: &PARAM
    parameter: Tm
    precip: false
    primary_threshold: 12
    threshold: 20
    threshold_type: abs
    unit: degC
    low_extreme: true
    min_exceedance_area: 0.0
  time_params: &TIME
    start: 1961
    end: 2025
    period: monthly
    ref_period: 1961-1990
    cc_period: 2010-2024
  dataset: &DATA
    dataset: SPARTACUS
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/SPARTACUS/reproj_UTM33N/v2.1/
    statpath: &statpath /home/wegnet/results/static/
    maskpath: *statpath
    mask_sub: masks/
    altitude_threshold: 1000

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: /home/wegnet/results/TEA_indicators_test/
  recalc_threshold: false
  recalc_daily: false
  decadal: false
  spreads: false
  decadal_only: false
  recalc_decadal: false

create_region_masks:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  gr_type: polygon
  shpfile: /data/reloclim/backup/GEO/shapefiles/OEKS15/good/AUSTRIA.shp
  target_sys: 32633
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/SPARTACUS/reproj_UTM33N/v2.1/SPARTACUSreg_orography.nc

regrid_SPARTACUS_to_WEGNext:
  <<: *PARAM
  <<: *DATA
  parameter: Tx
  raw_data_path: /data/reloclim/backup/ZAMG_SPARTACUS/data/v2024_v2.1/
  orography: false
  orog_file: /data/reloclim/backup/ZAMG_INCA/data/original/INCA_orog_corrected_y_dim.nc
  wegn_file: /var/wegnet/netcdf/WEA/WN_L2_DD_v7_UTM_TF1_UTC_2020-08.nc
  regridded_data_path: /home/wegnet/tmp/
