common_params:
  GeoRegion: &GR
    region: SEA
    full_region: false
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2024
    period: annual
    ref_period: 1961-1990
    cc_period: 2010-2024
  dataset: &DATA
    dataset: ERA5
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/
    statpath: &statpath /data/arsclisys/normal/clim-hydro/TEA-Indicators/static/
    maskpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ # *statpath
    mask_sub: masks/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: /data/users/hst/TEA-clean/TEA/paper_data/
  recalc_threshold: false
  recalc_daily: true
  hourly: true
  decadal: true
  recalc_decadal: true
  decadal_only: false
  spreads: true

create_region_masks:
  <<: *GR
  <<: *PATHS
  <<: *DATA
  <<: *PARAM
  <<: *TIME
  gr_type: polygon
  shpfile: /data/reloclim/backup/GEO/shapefiles/OEKS15/good/AUSTRIA.shp
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_orography.nc
  lsmfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_LSM.nc

