common_params:
  GeoRegion: &GR
    station: Deutschlandsberg
  parameter: &PARAM
    parameter: P24h_7to7
    precip: false
    threshold: 95
    threshold_type: perc
    unit: mm
    low_extreme: false
  time_params: &TIME
    start: 1877
    end: 2024
    period: annual
    # ref period from-to (inclusive)
    ref_period: 1961-1990
    # cc period from-to (inclusive)
    cc_period: 2010-2024
  dataset: &DATA
    dataset: HistAlp
  paths: &PATHS
    data_path: /data/users/hst/cdrDPS/station_data/
    result_path: &result_path /data/users/hst/TEA-clean/TEA/paper_data/

calc_TEA: &calc_TEA
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: *result_path
  recalc_daily: true
  hourly: false
  decadal: true
  spreads: true
  decadal_only: false
  recalc_decadal: true

natural_variability:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *PATHS
  <<: *DATA
  tea_path: /data/users/hst/TEA-clean/TEA/paper_data/
  outpath: *result_path
  stations: null
